FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_HUB_URL
ARG VITE_SERWIS_PUBLIC_ORIGIN
ARG VITE_GOOGLE_MAPS_API_KEY
ARG VITE_INBOUND_MAIL_DOMAIN
ARG VITE_N8N_RESIDENT_ORDER_WEBHOOK_URL
ARG VITE_N8N_VENDOR_ISSUE_WEBHOOK_URL
ARG VITE_CKOB_SYNC_WEBHOOK_URL
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_HUB_URL=$VITE_HUB_URL
ENV VITE_SERWIS_PUBLIC_ORIGIN=$VITE_SERWIS_PUBLIC_ORIGIN
ENV VITE_GOOGLE_MAPS_API_KEY=$VITE_GOOGLE_MAPS_API_KEY
ENV VITE_INBOUND_MAIL_DOMAIN=$VITE_INBOUND_MAIL_DOMAIN
ENV VITE_N8N_RESIDENT_ORDER_WEBHOOK_URL=$VITE_N8N_RESIDENT_ORDER_WEBHOOK_URL
ENV VITE_N8N_VENDOR_ISSUE_WEBHOOK_URL=$VITE_N8N_VENDOR_ISSUE_WEBHOOK_URL
ENV VITE_CKOB_SYNC_WEBHOOK_URL=$VITE_CKOB_SYNC_WEBHOOK_URL

RUN npm run build

FROM node:22-alpine
WORKDIR /app
RUN npm install -g serve@14
COPY --from=build /app/dist ./dist
ENV PORT=3000
EXPOSE 3000
CMD ["sh", "-c", "serve -s dist -l tcp://0.0.0.0:${PORT:-3000}"]
